//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("materialtype")]
    public partial class AddOrUpdateMaterialTypeReq 
    {

        /// <summary>
        /// 
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TypeAlias { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TypeName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public uint TypeLevel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public uint OrderIdx { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CodingExp { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DescExp { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public ushort Valid { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime UpdTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public ushort CodeRuleFlag { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public ushort AttachFlag { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int MacTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal MacPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public ushort ForBomAttFlag { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int type_id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int parent_id { get; set; }

        //todo:添加自己的请求字段
    }
}