//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流实例操作记录
	/// </summary>
      [Table("FlowInstanceOperationHistory")]
    public partial class FlowInstanceOperationHistory : Entity
    {
        public FlowInstanceOperationHistory()
        {
          this.InstanceId= string.Empty;
          this.Content= string.Empty;
          this.CreateDate= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
        }

        /// <summary>
	    /// 实例进程Id
	    /// </summary>
         [Description("实例进程Id")]
        public string InstanceId { get; set; }
        /// <summary>
	    /// 操作内容
	    /// </summary>
         [Description("操作内容")]
        public string Content { get; set; }
        /// <summary>
	    /// 创建时间
	    /// </summary>
         [Description("创建时间")]
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 创建用户主键
	    /// </summary>
         [Description("创建用户主键")]
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 创建用户
	    /// </summary>
         [Description("创建用户")]
        public string CreateUserName { get; set; }

        /// <summary>
        /// 审批时常（分钟）
        /// </summary>
        [Description("审批时常（分钟）")]
        public int? IntervalTime { get; set; }
        /// <summary>
        /// 审批结果
        /// </summary>
        [Description("审批结果")]
        public string ApprovalResult { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        public string Remark { get; set; }
        /// <summary>
        /// 审批阶段
        /// </summary>
        [Description("审批阶段")]
        public string ApprovalStage { get; set; }

        /// <summary>
        /// 当前节点id
        /// </summary>
        [Description("当前节点id")]
        public string ActivityId { get; set; }
        

    }
}