//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("ModuleFlowScheme")]
    public partial class ModuleFlowScheme : Entity
    {
        public ModuleFlowScheme()
        {
        }

        /// <summary>
        /// 模块Id
        /// </summary>
        public string ModuleId { get; set; }
        public Module Module { get; set; }
        /// <summary>
        /// 流程Id
        /// </summary>
        public string FlowSchemeId { get; set; }
        public FlowScheme FlowScheme { get; set; }
    }
}