//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:RenChun Xia
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;
using Infrastructure.AutoMapper;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    /// 合同文件类型表
    /// </summary>
    [Table("contractfiletype")]
    public partial class ContractFileType : Entity
    {
        public ContractFileType()
        {
            this.ContractApplyId = string.Empty;
            this.ContractSealId = string.Empty;
            this.FileType = string.Empty;
            this.ContractOriginalId = string.Empty;
            this.Remark = string.Empty;
        }

        /// <summary>
        /// 合同申请单Id
        /// </summary>
        [Description("合同申请单Id")]
        public string ContractApplyId { get; set; }

        /// <summary>
        /// 印章Id
        /// </summary>
        [Description("印章Id")]
        public string ContractSealId { get; set; }

        /// <summary>
        /// 文件类型
        /// </summary>
        [Description("文件类型")]
        public string FileType { get; set; }

        /// <summary>
        /// 合同原件Id
        /// </summary>
        [Description("合同原件Id")]
        public string ContractOriginalId { get; set; }

        /// <summary>
        /// 文件数量
        /// </summary>
        [Description("文件数量")]
        public int? FileNum { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 合同文件集合
        /// </summary>
        public virtual List<ContractFile> contractFileList { get; set; }
    }

    public class ContractFileQuery : Entity
    {
        public ContractFileQuery()
        {
            this.ContractSealId = string.Empty;
        }

        /// <summary>
        /// 印章Id
        /// </summary>
        [Description("印章Id")]
        public string ContractSealId { get; set; }

  
    }
}