//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:RenChun Xia
// </autogenerated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    /// 限制规则明细表
    /// </summary>
    [Table("paylimitruledetail")]
    public partial class PayLimitRuleDetail : Entity
    {
        public PayLimitRuleDetail()
        {
            this.PayLimitRuleId = string.Empty;
            this.Label = string.Empty;
            this.BracketLeft = string.Empty;
            this.Key = string.Empty;
            this.Contrast = string.Empty;
            this.Value = string.Empty;
            this.BracketRight = string.Empty;
            this.AndOr = string.Empty;
        }

        /// <summary>
        /// 限制规则Id
        /// </summary>
        [Description("限制规则Id")]
        public string PayLimitRuleId { get; set; }

        /// <summary>
        /// 规则序号
        /// </summary>
        [Description("规则序号")]
        public int? RuleNum { get; set; }

        /// <summary>
        /// 规则类型
        /// </summary>
        [Description("规则类型")]
        public int? RuleType { get; set; }

        /// <summary>
        /// 名称
        /// </summary>
        [Description("名称")]
        public string Label { get; set; }

        /// <summary>
        /// 左括号
        /// </summary>
        [Description("左括号")]
        public string BracketLeft { get; set; }

        /// <summary>
        /// 判定条件
        /// </summary>
        [Description("判定条件")]
        public string Key { get; set; }

        /// <summary>
        /// 表达式
        /// </summary>
        [Description("表达式")]
        public string Contrast { get; set; }

        /// <summary>
        /// 值
        /// </summary>
        [Description("值")]
        public string Value { get; set; }

        /// <summary>
        /// 右括号
        /// </summary>
        [Description("右括号")]
        public string BracketRight { get; set; }

        /// <summary>
        /// 并且或者
        /// </summary>
        [Description("并且或者")]
        public string AndOr { get; set; }
    }
}
