//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:RenChun Xia
// </autogenerated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    /// 付款条件保存信息表
    /// </summary>
    [Table("paytermsave")]
    public partial class PayTermSave : Entity
    {
        public PayTermSave()
        {
            this.PrepaUnit = string.Empty;
            this.BefShipUnit = string.Empty;
            this.GoodsToUnit = string.Empty;
            this.AcceptancePayDayUnit = string.Empty;
            this.AcceptancePayLimitUnit = string.Empty;
            this.QualityAssuranceLimitUnit = string.Empty;
            this.QualityAssuranceDayUnit = string.Empty;
            this.CreateUserId = string.Empty;
            this.CreateUserName = string.Empty;
            this.CreateTime = System.DateTime.Now;
            this.UpdateUserId = string.Empty;
        }

        /// <summary>
        /// 销售货到天数
        /// </summary>
        [Description("销售货到天数")]
        public int? SaleGoodsToDay { get; set; }

        /// <summary>
        /// 销售货到单位
        /// </summary>
        [Description("销售货到单位")]
        public string SaleGoodsToUnit { get; set; }

        /// <summary>
        /// 预付款天数
        /// </summary>
        [Description("预付款天数")]
        public int? PrepaDay { get; set; }

        /// <summary>
        /// 预付款单位
        /// </summary>
        [Description("预付款单位")]
        public string PrepaUnit { get; set; }

        /// <summary>
        /// 预付款百分比
        /// </summary>
        [Description("预付款百分比")]
        public decimal? PrepaPro { get; set; }

        /// <summary>
        /// 货前款天数
        /// </summary>
        [Description("货前款天数")]
        public int? BefShipDay { get; set; }

        /// <summary>
        /// 货前款单位
        /// </summary>
        [Description("货前款单位")]
        public string BefShipUnit { get; set; }

        /// <summary>
        /// 货前款百分比
        /// </summary>
        [Description("货前款百分比")]
        public decimal? BefShipPro { get; set; }

        /// <summary>
        /// 货到款天数
        /// </summary>
        [Description("货到款天数")]
        public int? GoodsToDay { get; set; }

        /// <summary>
        /// 货到款单位
        /// </summary>
        [Description("货到款单位")]
        public string GoodsToUnit { get; set; }

        /// <summary>
        /// 货到款百分比
        /// </summary>
        [Description("货到款百分比")]
        public decimal? GoodsToPro { get; set; }

        /// <summary>
        /// 验收款天数
        /// </summary>
        [Description("验收款天数")]
        public int? AcceptancePayDay { get; set; }

        /// <summary>
        /// 验收款天数单位
        /// </summary>
        [Description("验收款天数单位")]
        public string AcceptancePayDayUnit { get; set; }

        /// <summary>
        /// 验收款期限
        /// </summary>
        [Description("验收款期限")]
        public int? AcceptancePayLimit { get; set; }

        /// <summary>
        /// 验收款期限单位
        /// </summary>
        [Description("验收款期限单位")]
        public string AcceptancePayLimitUnit { get; set; }

        /// <summary>
        /// 验收款百分比
        /// </summary>
        [Description("验收款百分比")]
        public decimal? AcceptancePayPro { get; set; }

        /// <summary>
        /// 质保款天数
        /// </summary>
        [Description("质保款天数")]
        public int? QualityAssuranceDay { get; set; }

        /// <summary>
        /// 质保款天数单位
        /// </summary>
        [Description("质保款天数单位")]
        public string QualityAssuranceDayUnit { get; set; }

        /// <summary>
        /// 质保款期限
        /// </summary>
        [Description("质保款期限")]
        public decimal? QualityAssuranceLimit { get; set; }

        /// <summary>
        /// 质保款期限单位
        /// </summary>
        [Description("质保款期限单位")]
        public string QualityAssuranceLimitUnit { get; set; }

        /// <summary>
        /// 质保款百分比
        /// </summary>
        [Description("质保款百分比")]
        public decimal? QualityAssurancePro { get; set; }

        /// <summary>
        /// 付款条件
        /// </summary>
        [Description("付款条件")]
        public string GroupNum { get; set; }

        /// <summary>
        /// 创建人Id
        /// </summary>
        [Description("创建人Id")]
        public string CreateUserId { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        public string CreateUserName { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime? CreateTime { get; set; }

        /// <summary>
        /// 更新人Id
        /// </summary>
        [Description("更新人Id")]
        public string UpdateUserId { get; set; }
    }
}
