//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("ALR1")]
    public partial class ALR1 : Entity
    {
        public ALR1()
        {
          this.NameFrom= string.Empty;
          this.AddrFrom= string.Empty;
          this.NameTo= string.Empty;
          this.IsSMS= string.Empty;
          this.Address= string.Empty;
          this.Status= string.Empty;
          this.ObjType= string.Empty;
          this.ObjCode= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string NameFrom { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string AddrFrom { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string NameTo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string IsSMS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjCode { get; set; }
    }
}