//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("HEM2")]
    public partial class HEM2 : Entity
    {
        public HEM2()
        {
          this.fromDate= DateTime.Now;
          this.toDate= DateTime.Now;
          this.institute= string.Empty;
          this.major= string.Empty;
          this.diploma= string.Empty;
          this.EncryptIV= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? fromDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? toDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string institute { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string major { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string diploma { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? LogInstanc { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string EncryptIV { get; set; }
    }
}