//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("ITW1")]
    public partial class ITW1 : Entity
    {
        public ITW1()
        {
          this.Alert= string.Empty;
          this.NextDate= DateTime.Now;
          this.Alerted= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? UserSign { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? CycleCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Alert { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? NextDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? Time { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? DestUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Alerted { get; set; }
    }
}