//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("KPI2")]
    public partial class KPI2 : Entity
    {
        public KPI2()
        {
          this.Type= string.Empty;
          this.Color= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? KPIEntry { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? From { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? To { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Color { get; set; }
    }
}