//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("LIVI")]
    public partial class LIVI : Entity
    {
        public LIVI()
        {
          this.PatchLevel= string.Empty;
          this.Comment= string.Empty;
          this.LoadCustom= string.Empty;
          this.UpdateDate= DateTime.Now;
          this.InitMap= string.Empty;
          this.InitStd= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? Version { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string PatchLevel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Comment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string LoadCustom { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? LastMsgID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? UpdateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string InitMap { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string InitStd { get; set; }
    }
}