//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("OCSC")]
    public partial class OCSC : Entity
    {
        public OCSC()
        {
          this.Name= string.Empty;
          this.User= string.Empty;
          this.Password= string.Empty;
          this.URL= string.Empty;
          this.IsDefault= string.Empty;
          this.Port= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string User { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Password { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string URL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string IsDefault { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Port { get; set; }
    }
}