//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("OCSQ")]
    public partial class OCSQ : Entity
    {
        public OCSQ()
        {
          this.SeqType= string.Empty;
          this.FormID= string.Empty;
          this.ColToken= string.Empty;
          this.VisInForm= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string SeqType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string FormID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ColToken { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? VisualIndx { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string VisInForm { get; set; }
    }
}