//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("ODUN")]
    public partial class ODUN : Entity
    {
        public ODUN()
        {
          this.LetrFormat= string.Empty;
          this.EffctAftr= string.Empty;
          this.FeeCurr= string.Empty;
          this.MinBlnCurr= string.Empty;
          this.CalcIntert= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string LetrFormat { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string EffctAftr { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? LetterFee { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string FeeCurr { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? MinBalance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MinBlnCurr { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string CalcIntert { get; set; }
    }
}