//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("OTPW")]
    public partial class OTPW : Entity
    {
        public OTPW()
        {
          this.WizName= string.Empty;
          this.WizStatus= string.Empty;
          this.CreateDate= DateTime.Now;
          this.SaveDate= DateTime.Now;
          this.ExecDate= DateTime.Now;
          this.WizDate= DateTime.Now;
          this.SeriesStr= string.Empty;
          this.SubStr= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? WizNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string WizName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string WizStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? SaveDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? ExecDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? UserSign { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? Series { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public int? JETransId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? WizDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? RG23APart2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? RG23CPart2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? SeqCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? Serial { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string SeriesStr { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string SubStr { get; set; }
    }
}