//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("OWFER")]
    public partial class OWFER : Entity
    {
        public OWFER()
        {
          this.MsgID= string.Empty;
          this.MsgDetails= string.Empty;
          this.CreateDate= DateTime.Now;
          this.MsgTaskID= string.Empty;
          this.MsgErrSrc= string.Empty;
          this.Remark= string.Empty;
          this.MsgType= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MsgID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MsgDetails { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public short? UserSign { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MsgTaskID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MsgErrSrc { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string MsgType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? MsgInstID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? TemplateID { get; set; }
    }
}