//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("WLS2")]
    public partial class WLS2 : Entity
    {
        public WLS2()
        {
          this.ObjectType= string.Empty;
          this.ObjKey= string.Empty;
          this.Command= string.Empty;
          this.ObjSubType= string.Empty;
          this.ObjDetail= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? WFInstID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjectType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjKey { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Command { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? LogIns { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjSubType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string ObjDetail { get; set; }
    }
}