//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("WTC1")]
    public partial class WTC1 : Entity
    {
        public WTC1()
        {
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? WtAbsEntry { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? WTPercent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SumVatAmnt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SumDocTot { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SumBaseAmn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SumAccumAm { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public decimal? SumPercpAm { get; set; }
    }
}