//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain.Sap
{
    /// <summary>
	/// 
	/// </summary>
    [Table("XROBJ")]
    public partial class XROBJ : Entity
    {
        public XROBJ()
        {
          this.Name= string.Empty;
          this.Descriptio= string.Empty;
          this.Creator= string.Empty;
          this.CreateDate= DateTime.Now;
          this.ModifyDate= DateTime.Now;
          this.XmlId= string.Empty;
          this.XlsId= string.Empty;
          this.VariablesI= string.Empty;
          this.Reference= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Descriptio { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Creator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? ModifyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? ObjType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string XmlId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string XlsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string VariablesI { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Reference { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? RefType { get; set; }
    }
}