//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 售前需求申请相关部门信息
	/// </summary>
    [Table("beforesaledemanddeptinfo")]
    public partial class BeforeSaleDemandDeptInfo : Entity
    {
        public BeforeSaleDemandDeptInfo()
        {
          this.OrgId= string.Empty;
          this.OrgName= string.Empty;
          this.UserId = string.Empty;
          this.UserName = string.Empty;
          this.DevEstimate= 0;
          this.TestEstimate = 0;
        }        
        /// <summary>
        /// 售前需求申请单ID
        /// </summary>
        [Description("售前需求申请单ID")]
        [Browsable(false)]
        public int BeforeSaleDemandId { get; set; }
        /// <summary>
        /// 部门Id
        /// </summary>
        [Description("部门Id")]
        [Browsable(false)]
        public string OrgId { get; set; }
        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        public string OrgName { get; set; }
        /// <summary>
        /// 部门负责人Id
        /// </summary>
        [Description("部门负责人Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 部门负责人名字
        /// </summary>
        [Description("部门负责人名字")]
        public string UserName { get; set; }
        /// <summary>
        /// 开发预估工期
        /// </summary>
        [Description("开发预估工期")]
        public int DevEstimate { get; set; }
        /// <summary>
        /// 测试预估工期
        /// </summary>
        [Description("测试预估工期")]
        public int TestEstimate { get; set; }
        /// <summary>
        /// 是否需要开发实施 默认为0不需要
        /// </summary>
        [Description("是否需要开发实施")]
        public int IsDevDeploy { get; set; }
        /// <summary>
        /// 是否确认 默认0 确认1-表示执行研发提交
        /// </summary>
        [Description("是否确认 默认0 确认1-表示执行研发提交")]
        public int IsConfirm { get; set; }
        /// <summary>
        /// 研发意见
        /// </summary>
        [Description("研发意见")]
        public string DevOpinions { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public System.DateTime? UpdateTime { get; set; }
    }
}