//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 售前需求项目排期
	/// </summary>
    [Table("beforesaleproscheduling")]
    public partial class BeforeSaleProScheduling : BaseEntity<int>
    {
        public BeforeSaleProScheduling()
        {
          this.UserId= string.Empty;
          this.UserName= string.Empty;
          this.StartDate= DateTime.Now;
          this.EndDate= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        /// <summary>
        /// 关联项目Id
        /// </summary>
        [Description("关联项目Id")]
        [Browsable(false)]
        public int BeforeSaleDemandProjectId { get; set; }


        /// <summary>
        /// 关联申请流程Id
        /// </summary>
        [Description("关联申请流程Id")]
        [Browsable(false)]
        public int BeforeSaleDemandId { get; set; }

        /// <summary>
        /// 项目环节：0:需求，1:开发，2：测试
        /// </summary>
        [Description("项目环节：0:需求，1:开发，2：测试")]
        public int? Stage { get; set; }
        /// <summary>
        /// 负责人Id
        /// </summary>
        [Description("负责人Id")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 负责人名称
        /// </summary>
        [Description("负责人名称")]
        public string UserName { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        [Description("开始时间")]
        public System.DateTime? StartDate { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        [Description("结束时间")]
        public System.DateTime? EndDate { get; set; }

        /// <summary>
        /// 实际开始时间
        /// </summary>
        [Description("实际开始时间")]
        public System.DateTime? ActualStartDate { get; set; }
        /// <summary>
        /// 实际结束时间
        /// </summary>
        [Description("实际结束时间")]
        public System.DateTime? ActualEndDate { get; set; }
        /// <summary>
        /// 备用字段：需求文档/URL
        /// </summary>
        [Description("需求文档/URL")]
        public string ProjectDocURL { get; set; }
        /// <summary>
        /// 是否确认 默认0 确认1-表示已经确认提交
        /// </summary>
        [Description("是否确认 默认0 确认1-表示已经确认提交")]
        public int IsConfirm { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public System.DateTime? UpdateTime { get; set; }

        public override void GenerateDefaultKeyVal()
        {
        }

        public override bool KeyIsNull()
        {
            return Id == 0;
        }
    }
}