//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 差旅报销其他费用
	/// </summary>
    [Table("reimburseothercharges")]
    public partial class ReimburseOtherCharges : BaseEntity<int>
    {
        public ReimburseOtherCharges()
        {
          this.ReimburseInfoId= 0;
          this.ExpenseCategory= string.Empty;
          this.InvoiceNumber= string.Empty;
          this.Remark= string.Empty;
        }


        /// <summary>
        /// 报销单ID
        /// </summary>
        [Description("报销单ID")]
        [Browsable(false)]
        public int ReimburseInfoId { get; set; }
        /// <summary>
        /// 序号
        /// </summary>
        [Description("序号")]
        public int? SerialNumber { get; set; }
        /// <summary>
        /// 费用类别
        /// </summary>
        [Description("费用类别")]
        public string ExpenseCategory { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        [Description("金额")]
        public decimal? Money { get; set; }
        /// <summary>
        /// 发票号码
        /// </summary>
        [Description("发票号码")]
        public string InvoiceNumber { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 我的费用Id
        /// </summary>
        [Description("我的费用Id")]
        public string MyExpendsId { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime CreateTime { get; set; }
        public override void GenerateDefaultKeyVal()
        {
        }

        public override bool KeyIsNull()
        {
            return Id == 0;
        }
    }
}