//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    ///物流图片表
    /// </summary>
    [Table("expressagepicture")]
    public class ExpressagePicture : Entity
    {
        public ExpressagePicture()
        {
            this.ExpressageId = "";
            this.PictureId = "";

        }
        /// <summary>
        ///物流表Id
        /// </summary>
        [Description("")]
        public string ExpressageId { get; set; }

        /// <summary>
        ///图片id
        /// </summary>
        [Description("")]
        public string PictureId { get; set; }


    }
}