//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;
using OpenAuth.Repository.Domain.Material;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    /// 物料报价单物料列表
    /// </summary>
    [Table("quotationmaterial")]
    public class QuotationMaterial : Entity
    {
        public QuotationMaterial()
        {
            this.MaterialDescription = "";
            this.Id = "";
            this.Unit = "";
            this.MaterialCode = "";
            this.TotalPrice = 0;
            this.UnitPrice = 0;
            this.Remark = "";
            this.Count = 0;
            this.MaxQuantity = 0;
            this.Commission = 0;
        }

        /// <summary>
        ///物料报价单Id
        /// </summary>
        [Description("物料报价单Id")]
        public int QuotationId { get; set; }
        
        /// <summary>
        ///报价单设备Id
        /// </summary>
        [Description("报价单设备Id")]
        public string QuotationProductId { get; set; }
        
        /// <summary>
        ///物料描述
        /// </summary>
        [Description("物料描述")]
        public string MaterialDescription { get; set; }
        /// <summary>
        ///单位
        /// </summary>
        [Description("单位")]
        public string Unit { get; set; }

        /// <summary>
        ///物料编码
        /// </summary>
        [Description("物料编码")]
        public string MaterialCode { get; set; }

        /// <summary>
        ///总计
        /// </summary>
        [Description("总计")]
        public decimal? TotalPrice { get; set; }

        /// <summary>
        ///单价
        /// </summary>
        [Description("单价")]
        public decimal? UnitPrice { get; set; }

        /// <summary>
        ///备注
        /// </summary>
        [Description("备注")]
        public string Remark { get; set; }

        /// <summary>
        ///数量
        /// </summary>
        [Description("数量")]
        public int? Count { get; set; }

        /// <summary>
        ///最大数量
        /// </summary>
        [Description("最大数量")]
        public decimal? MaxQuantity { get; set; }

        /// <summary>
        ///折扣
        /// </summary>
        [Description("折扣")]
        public decimal? Discount { get; set; }

        /// <summary>
        ///销售价
        /// </summary>
        [Description("销售价")]
        public decimal? SalesPrice { get; set; }

        /// <summary>
        ///被替换物料
        /// </summary>
        [Description("被替换物料")]
        public string ReplaceMaterialCode { get; set; }

        /// <summary>
        ///是否新物料
        /// </summary>
        [Description("是否新物料")]
        public bool NewMaterialCode { get; set; }

        /// <summary>
        ///物料状态 1-更换 2-购买 3-赠送
        /// </summary>
        [Description("物料状态")]
        public int?  MaterialType { get; set; }

        /// <summary>
        ///折后价格
        /// </summary>
        [Description("折后价格")]
        public decimal? DiscountPrices { get; set; }

        /// <summary>
        ///仓库号
        /// </summary>
        [Description("仓库号")]
        public string WhsCode { get; set; }

        /// <summary>
        ///预估提成
        /// </summary>
        public decimal? Commission { get; set; }

        /// <summary>
        /// 物料附件
        /// </summary>
        public virtual List<QuotationMaterialPicture> QuotationMaterialPictures { get; set; }
    }
}