//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    ///退料单详细表
    /// </summary>
    [Table("ReturnnoteMaterialNumber")]
    public class ReturnnoteMaterialNumber : Entity
    {
        public ReturnnoteMaterialNumber()
        {
        }
        /// <summary>
        ///退料单物料d
        /// </summary>
        [Description("退料单物料d")]
        public string ReturnnoteMaterialId { get; set; }

        /// <summary>
        ///退仓的序列号
        /// </summary>
        [Description("退仓的序列号")]
        public string ReturnNumber { get; set; }

        /// <summary>
        ///领取的序列号
        /// </summary>
        [Description("领取的序列号")]
        public string RemoveNumber { get; set; }

    }
}