// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/EdgeAPI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EdgeAPI {

  /// <summary>Holder for reflection information generated from Protos/EdgeAPI.proto</summary>
  public static partial class EdgeAPIReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/EdgeAPI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EdgeAPIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3MvRWRnZUFQSS5wcm90bxIHRWRnZUFQSSIhCgdSZXF1ZXN0EhYK",
            "Dmpzb25fcGFyYW1ldGVyGAEgASgMIkUKCFJlc3BvbnNlEg8KB3N1Y2Nlc3MY",
            "ASABKAgSCwoDbXNnGAIgASgMEhsKBGRhdGEYAyABKAsyDS5FZGdlQVBJLkRB",
            "VEEihQIKBERBVEESKAoGbWFwX2RmGAEgAygLMhguRWRnZUFQSS5EQVRBLk1h",
            "cERmRW50cnkakAEKBFZlY1YSDAoEdHlwZRgBIAEoDBIQCgh2X2RvdWJsZRgC",
            "IAMoARIPCgd2X2Zsb2F0GAMgAygCEhAKCHZfdWludDMyGAQgAygNEhAKCHZf",
            "dWludDY0GAUgAygEEhAKCHZfc2ludDMyGAYgAygREhAKCHZfc2ludDY0GAcg",
            "AygSEg8KB3ZfYnl0ZXMYCCADKAwaQAoKTWFwRGZFbnRyeRILCgNrZXkYASAB",
            "KAkSIQoFdmFsdWUYAiABKAsyEi5FZGdlQVBJLkRBVEEuVmVjVjoCOAEy0gUK",
            "C0RhdGFTZXJ2aWNlEjMKCkdldERldkluZm8SEC5FZGdlQVBJLlJlcXVlc3Qa",
            "ES5FZGdlQVBJLlJlc3BvbnNlIgASNAoLR2V0VGVzdEluZm8SEC5FZGdlQVBJ",
            "LlJlcXVlc3QaES5FZGdlQVBJLlJlc3BvbnNlIgASOQoQR2V0VGVzdEluZm9D",
            "b3VudBIQLkVkZ2VBUEkuUmVxdWVzdBoRLkVkZ2VBUEkuUmVzcG9uc2UiABIz",
            "CgpHZXRSYXdEYXRhEhAuRWRnZUFQSS5SZXF1ZXN0GhEuRWRnZUFQSS5SZXNw",
            "b25zZSIAEjgKD0dldFJhd0RhdGFDb3VudBIQLkVkZ2VBUEkuUmVxdWVzdBoR",
            "LkVkZ2VBUEkuUmVzcG9uc2UiABI0CgtHZXRTdGVwRGF0YRIQLkVkZ2VBUEku",
            "UmVxdWVzdBoRLkVkZ2VBUEkuUmVzcG9uc2UiABI5ChBHZXRTdGVwRGF0YUNv",
            "dW50EhAuRWRnZUFQSS5SZXF1ZXN0GhEuRWRnZUFQSS5SZXNwb25zZSIAEjUK",
            "DEdldEN5Y2xlRGF0YRIQLkVkZ2VBUEkuUmVxdWVzdBoRLkVkZ2VBUEkuUmVz",
            "cG9uc2UiABI6ChFHZXRDeWNsZURhdGFDb3VudBIQLkVkZ2VBUEkuUmVxdWVz",
            "dBoRLkVkZ2VBUEkuUmVzcG9uc2UiABIuCgVHZXRSVBIQLkVkZ2VBUEkuUmVx",
            "dWVzdBoRLkVkZ2VBUEkuUmVzcG9uc2UiABIvCgZHZXRMb2cSEC5FZGdlQVBJ",
            "LlJlcXVlc3QaES5FZGdlQVBJLlJlc3BvbnNlIgASNAoLR2V0RWRnZUluZm8S",
            "EC5FZGdlQVBJLlJlcXVlc3QaES5FZGdlQVBJLlJlc3BvbnNlIgASMwoKQ29u",
            "dHJvbENtZBIQLkVkZ2VBUEkuUmVxdWVzdBoRLkVkZ2VBUEkuUmVzcG9uc2Ui",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EdgeAPI.Request), global::EdgeAPI.Request.Parser, new[]{ "JsonParameter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EdgeAPI.Response), global::EdgeAPI.Response.Parser, new[]{ "Success", "Msg", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EdgeAPI.DATA), global::EdgeAPI.DATA.Parser, new[]{ "MapDf" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EdgeAPI.DATA.Types.VecV), global::EdgeAPI.DATA.Types.VecV.Parser, new[]{ "Type", "VDouble", "VFloat", "VUint32", "VUint64", "VSint32", "VSint64", "VBytes" }, null, null, null, null),
            null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EdgeAPI.EdgeAPIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      jsonParameter_ = other.jsonParameter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "json_parameter" field.</summary>
    public const int JsonParameterFieldNumber = 1;
    private pb::ByteString jsonParameter_ = pb::ByteString.Empty;
    /// <summary>
    ///json格式的参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString JsonParameter {
      get { return jsonParameter_; }
      set {
        jsonParameter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (JsonParameter != other.JsonParameter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (JsonParameter.Length != 0) hash ^= JsonParameter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JsonParameter.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(JsonParameter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JsonParameter.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(JsonParameter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (JsonParameter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(JsonParameter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.JsonParameter.Length != 0) {
        JsonParameter = other.JsonParameter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            JsonParameter = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            JsonParameter = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EdgeAPI.EdgeAPIReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      success_ = other.success_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    /// <summary>
    ///是否成功 true:成功 false:失败
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private pb::ByteString msg_ = pb::ByteString.Empty;
    /// <summary>
    ///如果失败此存放错误消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::EdgeAPI.DATA data_;
    /// <summary>
    ///返回数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EdgeAPI.DATA Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::EdgeAPI.DATA();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            Msg = input.ReadBytes();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EdgeAPI.DATA();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            Msg = input.ReadBytes();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EdgeAPI.DATA();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DATA : pb::IMessage<DATA>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DATA> _parser = new pb::MessageParser<DATA>(() => new DATA());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DATA> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EdgeAPI.EdgeAPIReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DATA() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DATA(DATA other) : this() {
      mapDf_ = other.mapDf_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DATA Clone() {
      return new DATA(this);
    }

    /// <summary>Field number for the "map_df" field.</summary>
    public const int MapDfFieldNumber = 1;
    private static readonly pbc::MapField<string, global::EdgeAPI.DATA.Types.VecV>.Codec _map_mapDf_codec
        = new pbc::MapField<string, global::EdgeAPI.DATA.Types.VecV>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::EdgeAPI.DATA.Types.VecV.Parser), 10);
    private readonly pbc::MapField<string, global::EdgeAPI.DATA.Types.VecV> mapDf_ = new pbc::MapField<string, global::EdgeAPI.DATA.Types.VecV>();
    /// <summary>
    ///&lt;变量名,{值类型, [值1,值2...]}>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::EdgeAPI.DATA.Types.VecV> MapDf {
      get { return mapDf_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DATA);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DATA other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MapDf.Equals(other.MapDf)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MapDf.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mapDf_.WriteTo(output, _map_mapDf_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mapDf_.WriteTo(ref output, _map_mapDf_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += mapDf_.CalculateSize(_map_mapDf_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DATA other) {
      if (other == null) {
        return;
      }
      mapDf_.Add(other.mapDf_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mapDf_.AddEntriesFrom(input, _map_mapDf_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mapDf_.AddEntriesFrom(ref input, _map_mapDf_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DATA message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class VecV : pb::IMessage<VecV>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<VecV> _parser = new pb::MessageParser<VecV>(() => new VecV());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<VecV> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::EdgeAPI.DATA.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public VecV() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public VecV(VecV other) : this() {
          type_ = other.type_;
          vDouble_ = other.vDouble_.Clone();
          vFloat_ = other.vFloat_.Clone();
          vUint32_ = other.vUint32_.Clone();
          vUint64_ = other.vUint64_.Clone();
          vSint32_ = other.vSint32_.Clone();
          vSint64_ = other.vSint64_.Clone();
          vBytes_ = other.vBytes_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public VecV Clone() {
          return new VecV(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private pb::ByteString type_ = pb::ByteString.Empty;
        /// <summary>
        ///类型 根据类型选择使用下面的其中一个变量存储数据(double,float,uint32,uint64,sint32,sint64,bytes)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Type {
          get { return type_; }
          set {
            type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "v_double" field.</summary>
        public const int VDoubleFieldNumber = 2;
        private static readonly pb::FieldCodec<double> _repeated_vDouble_codec
            = pb::FieldCodec.ForDouble(18);
        private readonly pbc::RepeatedField<double> vDouble_ = new pbc::RepeatedField<double>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<double> VDouble {
          get { return vDouble_; }
        }

        /// <summary>Field number for the "v_float" field.</summary>
        public const int VFloatFieldNumber = 3;
        private static readonly pb::FieldCodec<float> _repeated_vFloat_codec
            = pb::FieldCodec.ForFloat(26);
        private readonly pbc::RepeatedField<float> vFloat_ = new pbc::RepeatedField<float>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<float> VFloat {
          get { return vFloat_; }
        }

        /// <summary>Field number for the "v_uint32" field.</summary>
        public const int VUint32FieldNumber = 4;
        private static readonly pb::FieldCodec<uint> _repeated_vUint32_codec
            = pb::FieldCodec.ForUInt32(34);
        private readonly pbc::RepeatedField<uint> vUint32_ = new pbc::RepeatedField<uint>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<uint> VUint32 {
          get { return vUint32_; }
        }

        /// <summary>Field number for the "v_uint64" field.</summary>
        public const int VUint64FieldNumber = 5;
        private static readonly pb::FieldCodec<ulong> _repeated_vUint64_codec
            = pb::FieldCodec.ForUInt64(42);
        private readonly pbc::RepeatedField<ulong> vUint64_ = new pbc::RepeatedField<ulong>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<ulong> VUint64 {
          get { return vUint64_; }
        }

        /// <summary>Field number for the "v_sint32" field.</summary>
        public const int VSint32FieldNumber = 6;
        private static readonly pb::FieldCodec<int> _repeated_vSint32_codec
            = pb::FieldCodec.ForSInt32(50);
        private readonly pbc::RepeatedField<int> vSint32_ = new pbc::RepeatedField<int>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<int> VSint32 {
          get { return vSint32_; }
        }

        /// <summary>Field number for the "v_sint64" field.</summary>
        public const int VSint64FieldNumber = 7;
        private static readonly pb::FieldCodec<long> _repeated_vSint64_codec
            = pb::FieldCodec.ForSInt64(58);
        private readonly pbc::RepeatedField<long> vSint64_ = new pbc::RepeatedField<long>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<long> VSint64 {
          get { return vSint64_; }
        }

        /// <summary>Field number for the "v_bytes" field.</summary>
        public const int VBytesFieldNumber = 8;
        private static readonly pb::FieldCodec<pb::ByteString> _repeated_vBytes_codec
            = pb::FieldCodec.ForBytes(66);
        private readonly pbc::RepeatedField<pb::ByteString> vBytes_ = new pbc::RepeatedField<pb::ByteString>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<pb::ByteString> VBytes {
          get { return vBytes_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as VecV);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(VecV other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          if(!vDouble_.Equals(other.vDouble_)) return false;
          if(!vFloat_.Equals(other.vFloat_)) return false;
          if(!vUint32_.Equals(other.vUint32_)) return false;
          if(!vUint64_.Equals(other.vUint64_)) return false;
          if(!vSint32_.Equals(other.vSint32_)) return false;
          if(!vSint64_.Equals(other.vSint64_)) return false;
          if(!vBytes_.Equals(other.vBytes_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Type.Length != 0) hash ^= Type.GetHashCode();
          hash ^= vDouble_.GetHashCode();
          hash ^= vFloat_.GetHashCode();
          hash ^= vUint32_.GetHashCode();
          hash ^= vUint64_.GetHashCode();
          hash ^= vSint32_.GetHashCode();
          hash ^= vSint64_.GetHashCode();
          hash ^= vBytes_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Type.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Type);
          }
          vDouble_.WriteTo(output, _repeated_vDouble_codec);
          vFloat_.WriteTo(output, _repeated_vFloat_codec);
          vUint32_.WriteTo(output, _repeated_vUint32_codec);
          vUint64_.WriteTo(output, _repeated_vUint64_codec);
          vSint32_.WriteTo(output, _repeated_vSint32_codec);
          vSint64_.WriteTo(output, _repeated_vSint64_codec);
          vBytes_.WriteTo(output, _repeated_vBytes_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Type.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Type);
          }
          vDouble_.WriteTo(ref output, _repeated_vDouble_codec);
          vFloat_.WriteTo(ref output, _repeated_vFloat_codec);
          vUint32_.WriteTo(ref output, _repeated_vUint32_codec);
          vUint64_.WriteTo(ref output, _repeated_vUint64_codec);
          vSint32_.WriteTo(ref output, _repeated_vSint32_codec);
          vSint64_.WriteTo(ref output, _repeated_vSint64_codec);
          vBytes_.WriteTo(ref output, _repeated_vBytes_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Type.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Type);
          }
          size += vDouble_.CalculateSize(_repeated_vDouble_codec);
          size += vFloat_.CalculateSize(_repeated_vFloat_codec);
          size += vUint32_.CalculateSize(_repeated_vUint32_codec);
          size += vUint64_.CalculateSize(_repeated_vUint64_codec);
          size += vSint32_.CalculateSize(_repeated_vSint32_codec);
          size += vSint64_.CalculateSize(_repeated_vSint64_codec);
          size += vBytes_.CalculateSize(_repeated_vBytes_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(VecV other) {
          if (other == null) {
            return;
          }
          if (other.Type.Length != 0) {
            Type = other.Type;
          }
          vDouble_.Add(other.vDouble_);
          vFloat_.Add(other.vFloat_);
          vUint32_.Add(other.vUint32_);
          vUint64_.Add(other.vUint64_);
          vSint32_.Add(other.vSint32_);
          vSint64_.Add(other.vSint64_);
          vBytes_.Add(other.vBytes_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Type = input.ReadBytes();
                break;
              }
              case 18:
              case 17: {
                vDouble_.AddEntriesFrom(input, _repeated_vDouble_codec);
                break;
              }
              case 26:
              case 29: {
                vFloat_.AddEntriesFrom(input, _repeated_vFloat_codec);
                break;
              }
              case 34:
              case 32: {
                vUint32_.AddEntriesFrom(input, _repeated_vUint32_codec);
                break;
              }
              case 42:
              case 40: {
                vUint64_.AddEntriesFrom(input, _repeated_vUint64_codec);
                break;
              }
              case 50:
              case 48: {
                vSint32_.AddEntriesFrom(input, _repeated_vSint32_codec);
                break;
              }
              case 58:
              case 56: {
                vSint64_.AddEntriesFrom(input, _repeated_vSint64_codec);
                break;
              }
              case 66: {
                vBytes_.AddEntriesFrom(input, _repeated_vBytes_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Type = input.ReadBytes();
                break;
              }
              case 18:
              case 17: {
                vDouble_.AddEntriesFrom(ref input, _repeated_vDouble_codec);
                break;
              }
              case 26:
              case 29: {
                vFloat_.AddEntriesFrom(ref input, _repeated_vFloat_codec);
                break;
              }
              case 34:
              case 32: {
                vUint32_.AddEntriesFrom(ref input, _repeated_vUint32_codec);
                break;
              }
              case 42:
              case 40: {
                vUint64_.AddEntriesFrom(ref input, _repeated_vUint64_codec);
                break;
              }
              case 50:
              case 48: {
                vSint32_.AddEntriesFrom(ref input, _repeated_vSint32_codec);
                break;
              }
              case 58:
              case 56: {
                vSint64_.AddEntriesFrom(ref input, _repeated_vSint64_codec);
                break;
              }
              case 66: {
                vBytes_.AddEntriesFrom(ref input, _repeated_vBytes_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
