//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    [Table("usersign")]
    public partial class UserSign : BaseEntity<int>
    {
        public UserSign()
        {
          this.UserId= string.Empty;
          this.UserName= string.Empty;
          this.PictureId= string.Empty;
        }

        
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string UserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string UserName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string PictureId { get; set; }

        public override void GenerateDefaultKeyVal()
        {
            throw new NotImplementedException();
        }

        public override bool KeyIsNull()
        {
            return Id == 0;
        }
    }
}