//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.App.Serve.Response;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 
	/// </summary>
    [Table("myexpends")]
    public partial class AddOrUpdateMyExpendsReq
    {

        /// <summary>
        /// 
        /// </summary>
        public int? Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FeeType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? SerialNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TrafficType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Transport { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string From { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string To { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Money { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InvoiceNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? Days { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? TotalMoney { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ExpenseCategory { get; set; }

        /// <summary>
        /// 附件表
        /// </summary>
        public virtual List<ReimburseAttachmentResp> ReimburseAttachments { get; set; }


        /// <summary>
        /// 删除附件
        /// </summary>
        public virtual List<string> fileid { get; set; }

        //todo:添加自己的请求字段
    }
}